# Generated by Django 5.2.11 on 2026-02-15 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('COMPANY', 'Empresa'), ('CANDIDATE', 'Candidato'), ('GESTOR', 'Gestor'), ('ALUNO', 'Aluno')], default='CANDIDATE', max_length=20),
        ),
    ]
