# Generated by Django 5.2.11 on 2026-02-15 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('COMPANY', 'Empresa'), ('CANDIDATE', 'Candidato')], default='CANDIDATE', max_length=20),
        ),
    ]
