# Generated by Django 5.2.11 on 2026-02-16 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='type',
            field=models.CharField(choices=[('candidate', 'Candidato'), ('company', 'Empresa'), ('gestor', 'Gestor'), ('aluno', 'Aluno')], max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('company', 'Empresa'), ('candidate', 'Candidato'), ('gestor', 'Gestor'), ('aluno', 'Aluno')], default='candidate', max_length=20),
        ),
    ]
