# Generated by Django 5.2.11 on 2026-08-21 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_ano_conclusao_profile_ano_inicio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('ativo', 'Ativo'), ('inativo', 'Inativo')], default='ativo', max_length=10),
        ),
    ]
