"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from dotenv import load_dotenv

load_dotenv()

from pathlib import Path


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
# Antes vinha hardcoded True e ALLOWED_HOSTS vazio — ou seja, mesmo o .env
# já tendo DEBUG e ALLOWED_HOSTS prontos para produção, settings.py nunca os
# lia. Agora os dois vêm do ambiente; sem as variáveis definidas, o padrão é
# o mais seguro (DEBUG=False, nenhum host liberado), não o mais permissivo.
DEBUG = os.getenv('DEBUG', 'False').strip().lower() == 'true'

ALLOWED_HOSTS = [h.strip() for h in os.getenv('ALLOWED_HOSTS', '').split(',') if h.strip()]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework.authtoken',
    'corsheaders',     # Se estiver usando  
    'django_filters',
    'companies',
    'jobs',
    'pdf',
    'resumes',
    'users.apps.UsersConfig',
    'captcha',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # Se estiver usando
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'

# Autenticação
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Fortaleza'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

#STATIC_ROOT = BASE_DIR / 'staticfiles'  # Pasta onde collectstatic vai colocar arquivos

STATICFILES_DIRS = [
   # BASE_DIR / 'static',  # Pasta de arquivos estáticos durante desenvolvimento
]
# Media files (Upload de usuários)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Traduções
LOCALE_PATHS = [BASE_DIR / 'locale']

# CONFIGURAÇÃO DE E-MAIL
# O app não usa mais o `send_mail()` nativo do Django para nada que o
# usuário precisa receber — os dois lugares que ainda usavam (aviso de novo
# login em users/signals.py, mudança de status de candidatura em
# jobs/views.py) foram migrados para `enviar_email_async` (Resend), a mesma
# função já usada pelo restante do app. EMAIL_BACKEND fica no console só
# como fallback inerte do Django (nada relevante passa por ele hoje).
RESEND_API_KEY = os.getenv("RESEND_API_KEY")

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

from django.contrib.messages import constants as messages

MESSAGE_TAGS = {
    messages.DEBUG: 'secondary',
    messages.INFO: 'info',
    messages.SUCCESS: 'success',
    messages.WARNING: 'warning',
    messages.ERROR: 'danger',
}

from datetime import timedelta

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    # Limites de tentativas por IP nas rotas AllowAny mais sensíveis (login,
    # cadastro, reset e confirmação de conta por PIN). Cada rota usa sua
    # própria throttle class (ver users/throttles.py) com esta 'scope'.
    # Antes não existia nenhum limite — o PIN de 6 dígitos ficava exposto a
    # força-bruta sem nenhuma fricção.
    'DEFAULT_THROTTLE_RATES': {
        'login': '10/min',
        'register': '5/min',
        'password_reset': '5/min',
        'password_reset_confirm': '5/min',
        'confirm_registration': '5/min',
    },
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'CHECK_REVOCATION': False,
    'UPDATE_LAST_LOGIN': True,
}

AUTH_USER_MODEL = 'users.User'

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend', # Mantém o padrão
    'users.backends.EmailOrPinBackend',          # Adiciona o seu novo tradutor
]
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173", # Porta comum do Vite
    "http://127.0.0.1:5173",
]


# IMPORTANTE: Para o React conseguir ler o cabeçalho de autenticação se necessário
CORS_ALLOW_HEADERS = [
    "accept",
    "authorization",
    "content-type",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
]

# Endurecimento de transporte — só entra em vigor quando DEBUG=False (ou
# seja, nunca no dev local, onde não há HTTPS). Sem isso, um deploy fora do
# localhost sairia sem HSTS/redirect para HTTPS/cookies seguros por padrão.
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 60 * 60 * 24 * 30  # 30 dias
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True